# Generated by Django 3.1 on 2021-01-15 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('column_separ', models.PositiveSmallIntegerField(choices=[(0, 'Comma'), (1, 'Dot')], default=0)),
                ('str_char', models.PositiveSmallIntegerField(choices=[(0, 'Doublequote'), (1, 'Singlequote')], default=0)),
                ('column_name', models.CharField(max_length=64)),
                ('column_name1', models.CharField(max_length=64)),
                ('column_name2', models.CharField(max_length=64)),
                ('column_name3', models.CharField(max_length=64)),
                ('column_name4', models.CharField(max_length=64)),
                ('column_type', models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0)),
                ('column_type1', models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0)),
                ('column_type2', models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0)),
                ('column_type3', models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0)),
                ('column_type4', models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ready'), (1, 'Processing')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newschema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
