# Generated by Django 3.1 on 2021-01-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschema',
            name='row_number',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
