# Generated by Django 3.1 on 2021-01-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVmaker', '0002_newschema_row_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newschema',
            name='file',
            field=models.FileField(null=True, upload_to='text/'),
        ),
    ]
