# Generated by Django 3.1 on 2021-01-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSVmaker', '0003_newschema_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newschema',
            name='row_number',
        ),
    ]
