# Generated by Django 3.1 on 2021-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVmaker', '0004_remove_newschema_row_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
