# Generated by Django 3.1 on 2021-01-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSVmaker', '0005_auto_20210118_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschema',
            name='column_name',
            field=models.CharField(max_length=64, verbose_name='Column name'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_name1',
            field=models.CharField(max_length=64, verbose_name='Column name'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_name2',
            field=models.CharField(max_length=64, verbose_name='Column name'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_name3',
            field=models.CharField(max_length=64, verbose_name='Column name'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_name4',
            field=models.CharField(max_length=64, verbose_name='Column name'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_separ',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Comma(,)'), (1, 'Dot(.)')], default=0, verbose_name='Column separator'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_type1',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_type2',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_type3',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='column_type4',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full name'), (1, 'Age'), (2, 'Company'), (3, 'Job'), (4, 'Phone number'), (5, 'Country')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='newschema',
            name='str_char',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Double-quote(")'), (1, "Single-quote(')")], default=0, verbose_name='String character'),
        ),
    ]
